
level_1 = [
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XX          X          X           X            XX",
    "XX          X        A X   E            E       XX",
    "XX    P                X                     E  XX",
    "XX                   A X      E    X            XX",
    "XX          X          X           X            XX",
    "XXXXXXXXXXXXXXXXX  XXXXXXXXXX    XXX       E    XX",
    "XX              X                  X            XX",
    "XX   A T  T A   X                H X  E         XX",
    "XX              X                  X        E   XX",
    "XX              XXXXXX   XXXXXXXXXXXXXXXX  XXXXXXX",
    "XX              X          X      X             XX",
    "XX   E    E     X          X    T X             XX",
    "XXXXXXX    XXXXXX          X    T XA   E        XX",
    "XX        E          E     X    T XA            XX",
    "XX                         X    T XA         E  XX",
    "XX  E           X    E     X    T X     E       XX",
    "XX              X          X      X             XX",
    "XXX  XXXXXXXXXXXXXXXXXXXXXXXXXXOXXXXXXXXXXXXX   XX",
    "XX              X    H  H    X              X   XX",
    "XX              X            X              X   XX",
    "XX              X     E     AX    E             XX",
    "XX      E                   KX                  XX",
    "XX                          AX       E          XX",
    "XX              X         E  X                  XX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXX",
    "XX            X              X     X            XX",
    "XX    H T H   X      E                     E    XX",
    "XX  E   E     X                        E        XX",
    "XX            X          E   XXXXXXX            XX",
    "XX            X   E          X    EX            XX",
    "XX        E                  X E        E       XX",
    "XX   E                E      X                  XX",
    "XXXXXXXXXXXXXXXXXXXXX  XXXXXXXX   XXXXXXXXXXXXXXXX",
    "XX            X              X       E          XX",
    "XX   T   T    X  E         E X               E  XX",
    "XX     T      O              X            E     XX",
    "XX   T   T    X    E    E    X      E           XX",
    "XX            X   A  A  A    X               E  XX",
    "XXXOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXX",
    "XX            X              X        X         XX",
    "XX  E              E             E        E     XX",
    "XX      E                E                   E  XX",
    "XX         E  X    E         X    E   X         XX",
    "XX   E        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XX            X      E               E          XX",
    "XX      E                     E               D XX",
    "XX            X   E      E              E       XX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
]

levels = [level_1]