
level_1 = [
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XX          X          X          XX            XX",
    "XX          X          X   E            E       XX",
    "XX    P            A   X                     E  XX",
    "XX                     X      E   XX            XX",
    "XX          X          X          XX            XX",
    "XXXXXXXXXXXXXXXXX  XXXXXXXX    XXXXX       E  A XX",
    "XX     T  T     X                  X            XX",
    "XX   A      A   X                 AX  E         XX",
    "XX              X                  X        E   XX",
    "XX              XXXXXX   XXXXXXXXXXXXXXXX  XXXXXXX",
    "XX              X          X      X             XX",
    "XX   E    E     X          X    T X             XX",
    "XXXXXXX    XXXXXX          X    T X    E        XX",
    "XX        E          E     O    T X             XX",
    "XX                         X    T XA         E  XX",
    "XX  E           X    E     X    T X     E       XX",
    "XX              X          X      X             XX",
    "XXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XX",
    "XX              X            X              X   XX",
    "XX              X            X              X   XX",
    "XX              X     E     AX    E             XX",
    "XX      E                   KX A                XX",
    "XX                          AX       E          XX",
    "XX              X         E  X            A     XX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXX",
    "XX  A T A T A X              X     X            XX",
    "XX            X      E                     E    XX",
    "XX  E   E     X                        E       AXX",
    "XX            X          E   X E   X            XX",
    "XX            X   E          X    EX           AXX",
    "XX        E                  X     X    E       XX",
    "XX   E                E      X     X            XX",
    "XXXXXXXXXXXXXXXXXXXXX  XXXXXXXX   XXXXXXXXXXXXXXXX",
    "XX            X              X       E          XX",
    "XX   T   T    X  E         E XA              E  XX",
    "XX     T      O              X            E     XX",
    "XX   T   T    X    E    E    XA     E           XX",
    "XX            X      A       X               E  XX",
    "XXXOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXX",
    "XX            X              X        X         XX",
    "XX  E              E             E        E     XX",
    "XXA     E                E                   E  XX",
    "XX         E  X    E  A      X    E   X    A    XX",
    "XX   E        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXA           X      E               E          XX",
    "XX      E                     E                DXX",
    "XX            X   E      E              E       XX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
]

level_2 = [
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XU          XXXXXXXX   XXXXXXXX            XXXXXXX",
    "X     E     XXXXXXX   XXXXXXXX          E IIXXXXXX",
    "XXXXXXXXIIIIXXXXXX  EXXXXXXXXXIXXXXXXXXXXX    XXXX",
    "XXXXXXXX    XXXXX   XXXXXXXXXX XT   XXXXXXX    XXX",
    "XXXXXXXX    XXXX   XXXXXXXXXXXX      XXXXXXX   XXX",
    "XXXXXXXX    XXX   XXXXXXXXXXXX   XX   XXXXXXX   XX",
    "XXXXXXX     XXIIIXXXXXXXXXXXX   XXXX   XXXXXX   XX",
    "XXXXXX       T     XXXXXXXXX   XXXXXX   XXXXX   XX",
    "XXXXX   XXXXXXXXXIIXXXXXXXX   XXXXXXXX   XXX  TXXX",
    "XXXX   XXXXXXXXXX  XXXXXXX   XXXXXXXXXX   X   XXXX",
    "XXX   XXXXXXXXXXX  XXXXXX   XXXXXXXXXXXX     XXXXX",
    "XX   XXXXXXXXXXXX  XXXXXX   XXXXXXXXXXXXX   XXXXXX",
    "XX   XXXXXXXXXXE   XXXXXX   XXXXT          XXXXXXX",
    "XX   XXXXXXXXXX    XXXXXX   XXXX         XXXXXXXXX",
    "XX   XXXXXXXXXXXXXXXXXXXX   XXXX         XXXXXXXXX",
    "XX   XXXXXXXXXXXXXXXXXXXX   XXXX        P XXXXXXXX",
    "XX   XXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXX",
    "XX   XXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXX",
    "XX   XXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXX",
    "XX   XXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXX",
    "XX   XXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXX",
    "XX   XXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXX",
    "XX   XXXXXXXXXX                   E            XXX",
    "XX   XXXXXXXXXX    E                           XXX",
    "XX   XXXXXXXXXXIIIXXXXXXXXXXXXXXXXXXXXXXXXXXIIIXXX",
    "XXXT  XXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXX   XXX",
    "XXXX    XXXXXXXXX   XXXXXXXXX  T  XXXXXXXXXX   XXX",
    "XXXXX    XXXXXXXXX   XXXXXXX   E   XXXXXXXXX   XXX",
    "XXXXXX    XXXXXXXXX   XXXXXXIIIXXII            XXX",
    "XXXXXXX    XXXXXXXXX   XXXXX   XX      T       XXX",
    "XXX   XXX  XXXXXXXXXX          XX    XXXXXXX   XXX",
    "XXX   XXX         XXXX                XXXXXX   XXX",
    "XXX   XXXXXXXXXX  XXXXXXXXXXXXXXXXX   XXXXXX   XXX",
    "XXXX   XXXXXXXXX  XXXXXXXXXXXXXXXXX   XXXXXX   XXX",
    "XXXXX   XXXXXXXX  XXXXXXXXXXXXXXXXX   XXXXXX   XXX",
    "XXXXXX   XXXXXXX    XXXXXXXXXXXXXX   XXXXXXX   XXX",
    "XXXXXXX    T        XXXXXXXXXXXX    XXXXXXXX   XXX",
    "XXXXXXXXX       XX   XXXXXXXXXXX    XXXXXXXX   XXX",
    "XXXXXXXX       XXXX  TXXXXXXXXX   XXXXXXXXXX   XXX",
    "XXXXXXX   XXXXXXXXXX              XXXXXXXXXX   XXX",
    "XXXXXX   XXXXXXXXXXXX             XXXXXXXXXX   XXX",
    "XXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXX",
    "XXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXX",
    "XXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXXXX",
    "XXXX   XXXXXXXXX             XXXXXXXXXXXX   XXXXXX",
    "XXXX   XXXXXXXXX              XXXXXXXXX    XXXXXXX",
    "XXXXIIIXXXXXXXXXIIIXXXXXXXXX   XXXXXXX   XXXXXXXXX",
    "XXXX               XXXXXXXXXX            XXXXXXXX",
    "XXXX     E         XXXXXXXXXXX      T    XXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
]

level_3 = [
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XP         E I     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "X            I     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX S   XXT                   E       X",
    "XXXXXXXXXXXXXX  S  I            E                X",
    "X           TX     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XE           I     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "X  XXXXXXXXXXX     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "X  XXXXXXXXXXX     XXXXXX         T              X",
    "XXXI      E   I    XXXXXXISII     E          II  X",
    "X                 TXXXXXX    XXXXXXXXXXXXXXXX  XXX",
    "X  S XXXXXXXXXXXXXXXXXXXE   XXXXXXXXXXXXXXXXX  XXX",
    "X   XXXXXXXXXXXXXXT     IIXXXXXXXXXXXXXXXXXXX  XXX",
    "X IXXXXXXXXXXXXXXX      XXXX                S  XXX",
    "X EXXXXXXXXXXXXXXX     XXXXX  I  E          I  XXX",
    "X  XXXXXXXXXXXXXXX    XX       TXXXXXXXXXXXXX  XXX",
    "X IXXXXXXXXXXXXXXX   XXX  XXXXXXX   XXXXXXXXXT XXX",
    "X                 S  XXX  XXXXXXX   XXXXXXXXX  XXX",
    "X       I          E XXX   I  EXX   XXXXXXXXXIIXXX",
    "X  XXXXXXXXXXXXXXXXXXXXXXXXX   XX  E           XXX",
    "X TXXXX                   XX   XX   E           XX",
    "X  XXXX                 E XX   XXXXXXXXXXXXXXXXXXX",
    "X  XXXXXXXXXXXXXXXXXXXIIIIXX   XXXXXXXXXXXXXXXXXXX",
    "X  XXXXXXXXXXXXXXXXXXX    XXES XXXXXXXXXXXXXXXXXXX",
    "X                         XXXXI                TXX",
    "X       I         E       XXXXXE                XX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXIIXX",
    "X         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XX",
    "XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XX",
    "XXXXXXXXX  E    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XX",
    "XXXXXXXXXXXXXXXI XXXXXXXXXX        E        SI  XX",
    "XX         XXXXX  XXXXXXXXX          E       I  XX",
    "XXEXXXXXXX XXXXX          XXIIXXXXXXXXXXXXXXXX  XX",
    "XX XXXXXXXT XXXXXXXXXXXX  XX  XXXXXXXXXXXXXXXXX XX",
    "XXU XXXXXX  XXXXXXXXXXX  XXX   XXXXXXXXXXXXXXXT XX",
    "XXXXXXXXXX  XXXXXXXXXXXXT XXX   XXXXXXXXX  XXXEEXX",
    "XXXXXXXXXX  XXXXXXXXXXXX  XXXX I XXXXXXXX  XXX  XX",
    "XXXT      I S         TS  XXXXX   XXXXXXX  XXX  XX",
    "XXX  E    I               XXXXX     E      XXX  XX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXEXXXXXXXXXXXXXXXXXXXX  XX",
    "X                     XX                   TSI  XX",
    "X  XXXXXXXXXXXXXXXXX  XX                   E I  XX",
    "X  XX            EXX  XXXXXXXXXX  XXXXXXXXXXXX  XX",
    "X  XX XXXXXXXXXXX XX  XXXXXXXXXT XXXXXXXXXXXXX  XX",
    "X  XX XXXXXXXXXXX XX  XXXXXXXX  XXXXXXXXXXXXXX  XX",
    "X  XX XXXXXXXXXXX XX  XXXXXXX  XXXXXXXXXXXXXXX  XX",
    "X  XX XXXXXXXXXXX XXIIXXXXXX  XXXXXXXXXXXXXXXX  XX",
    "X  XX XXXXXXXXXXX XX     E   S       I          XX",
    "XIIXX XXXXXXXXXXX XX         E       I         TXX",
    "X                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
]

level_4 = [
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XP     I     E       I          XXXXXX           X",
    "X                               XXXXXX           X",
    "X  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  X",
    "XIIXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  X",
    "X  XX    I     E      I      XXT            CXX  X",
    "X  XX         S              XX  I  E     I  XX  X",
    "X EXX SXXXXXXXXXXXXXC XXXXXXXXXXXXX  XXXXXXS XX SX",
    "X  XX  XXXXXXXXXXXXXIIXXXXXXXXXXXXXS XXXXXX  XX  X",
    "XS XX  XX      E                 XX      XX  XX  X",
    "X  XX  XX  E                     XX      XX  XXS X",
    "X  XX  XX  XXXXXXXXXXXXXXXXXXXXXXXXXXXX  XX  XX  X",
    "X  XX  XX  XXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXIIXX  X",
    "X  XX  XX  XX   I       E IS          T  XX    I X",
    "X  XX  XX  XX          S      CS         XX   EI X",
    "X  XXIIXX  XX  XXXXXXXXXXXXXXXXXXXX  XX  XXIIXX  X",
    "X  XX  XX  XX  XXXXXXXXXXXXXXXXXXXX  XX  XX  XX  X",
    "XIIXX  XX  XX  XX            XX  XX  XXS XXT XX  X",
    "X  XX  XX  XX  XXII E      X XX  XX  XX  XXE XX  X",
    "X  XX  XXXXXX  XXS XX  XXXX XXX  XX  XX  XX  XX  X",
    "X  XX  XXXXXX  XX  XX XXXXX XXX  XX  XX  XX  XX  X",
    "X  XXE XX   I  XX  XX XXXXX  XX  XXXXXX  XX  XXS X",
    "X  XX  XX   I  XX  XX  X  X  XXIIXXXXXX  XX  XX  X",
    "X  XX  XX SXX  XX  XXX  SX   XX  E   XXXXXX EXX SX",
    "X  XXIIXX  XX  XX  XXCX  X X XXIIX IIXXXXXX  XX  X",
    "X  XX  XXS XXIIXX  XX   X X  XX  XX  XX  XXXXXXS X",
    "X  XX  XX  XXE XX  XXTXX    XXX  XX  XXC XXXXXX  X",
    "X  XX  XX SXX  XX  XX     X  XX  XXS  I  XX  XX TX",
    "X  XX  XX  XX  XX  XX   X X      XX   I  XX  XX  X",
    "X  XX  XX  XX  XX  XX    X   X   XX  XX   I  XX  X",
    "X  XX  XX  XX  XX  XX  XXXXXXXXXXXXC XXE  I  XX  X",
    "X  XX  XX  XX  XXIIXXXXXXXXXXXXXXXXE XXIIXX  XX  X",
    "X  XX  XX  XX  XX   E       I    XX  XX  XX SXX  X",
    "X  XX  XX  XX EXX                XX  XX  XX      X",
    "X  XX  XX EXX  XXXXXXXXXXXXX SXXXXXXXXXXXXX      X",
    "X  XX  XX  XX  XXXXXXXXXXXXXISXXXXXXXXXXXXXC XXIIX",
    "X  XX  XX  XX  I     XX            E     XX  XX EX",
    "X  XX  XX  XX  C     XX      E           XX  XX  X",
    "X  XX  XX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXIIXXXXXX  X",
    "X  XX  XXE XXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXX",
    "X  XX  XXII      XX       E        XX    C   XXXXX",
    "X  XX  XX        XXC               XXE       XXXXX",
    "X  XX  XX  XXXXXXXXXXXXXXXXXXXIIXXXXXXXXXXXIIXXXXX",
    "X  XX  XX  XXXXXXXXXXXXXXXXXXX  XXXXXXXXXXX  XXC X",
    "X  SS  XX  I    E         T  I       XX      XX  X",
    "X     TXX                 S          XXE     XX  X",
    "X  XXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXX SXXXX  X",
    "X  XXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXIIXXXX  X",
    "X                                  XXXX   E      X",
    "X         I           E      I     XXXXT      TU X",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
]

levels = [level_1, level_2, level_3, level_4]